### ISSUE TITLE
Processing large number of VCF files

### ISSUE THREAD

**Issue by duceppemo** [USDA-VS/snp_analysis#7]
When using the "all" option on a high number of VCF file (4460), I get the following error.
`All_VCFs table dimensions: (4298, 63111)
All_VCFs RAxML running...
ERROR: missing ')' at line 0 near '5MIDNRdeerMontm_zc'
cat: write error: Broken pipe
All_VCFs Getting map quality...
All_VCFs annotating from annotation dictionary... D20181218_1709
concurrent.futures.process._RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/home/bioinfo/miniconda3/envs/vsnp/lib/python3.6/concurrent/futures/process.py", line 175, in _process_worker
    r = call_item.fn(*call_item.args, **call_item.kwargs)
  File "/home/bioinfo/miniconda3/envs/vsnp/lib/python3.6/concurrent/futures/process.py", line 153, in _process_chunk
    return [fn(*args) for args in chunk]
  File "/home/bioinfo/miniconda3/envs/vsnp/lib/python3.6/concurrent/futures/process.py", line 153, in <listcomp>
    return [fn(*args) for args in chunk]
  File "/home/bioinfo/vSNP/functions.py", line 2720, in get_snps
    excelwriter(out_sort) #***FUNCTION CALL #sort
  File "/home/bioinfo/vSNP/functions.py", line 2889, in excelwriter
    wb.close()
  File "/home/bioinfo/miniconda3/envs/vsnp/lib/python3.6/site-packages/xlsxwriter/workbook.py", line 306, in close
    self._store_workbook()
  File "/home/bioinfo/miniconda3/envs/vsnp/lib/python3.6/site-packages/xlsxwriter/workbook.py", line 677, in _store_workbook
    xlsx_file.write(os_filename, xml_filename)
  File "/home/bioinfo/miniconda3/envs/vsnp/lib/python3.6/zipfile.py", line 1645, in write
    with open(filename, "rb") as src, self.open(zinfo, 'w') as dest:
  File "/home/bioinfo/miniconda3/envs/vsnp/lib/python3.6/zipfile.py", line 1378, in open
    return self._open_to_write(zinfo, force_zip64=force_zip64)
  File "/home/bioinfo/miniconda3/envs/vsnp/lib/python3.6/zipfile.py", line 1488, in _open_to_write
    self._writecheck(zinfo)
  File "/home/bioinfo/miniconda3/envs/vsnp/lib/python3.6/zipfile.py", line 1604, in _writecheck
    " would require ZIP64 extensions")
zipfile.LargeZipFile: Filesize would require ZIP64 extensions
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/bioinfo/vSNP/vSNP.py", line 227, in <module>
    functions.run_script2(arg_options)
  File "/home/bioinfo/vSNP/functions.py", line 1696, in run_script2
    for samples_in_fasta in pool.map(get_snps, directory_list, itertools_repeat(arg_options), chunksize=5):
  File "/home/bioinfo/miniconda3/envs/vsnp/lib/python3.6/concurrent/futures/process.py", line 366, in _chain_from_iterable_of_lists
    for element in iterable:
  File "/home/bioinfo/miniconda3/envs/vsnp/lib/python3.6/concurrent/futures/_base.py", line 586, in result_iterator
    yield fs.pop().result()
  File "/home/bioinfo/miniconda3/envs/vsnp/lib/python3.6/concurrent/futures/_base.py", line 432, in result
    return self.__get_result()
  File "/home/bioinfo/miniconda3/envs/vsnp/lib/python3.6/concurrent/futures/_base.py", line 384, in __get_result
    raise self._exception
zipfile.LargeZipFile: Filesize would require ZIP64 extensions`

**Comment by duceppemo** [comment]
I think you solve this by adding "allowZip64 = True" to your zipfile commands.

**Comment by stuber** [comment]
Say more about using "allowZip64 = True".  Not understanding.

**Comment by duceppemo** [comment]
`newZip = zipfile.ZipFile(unmapped_read1gz, 'w')`
needs to be replaced by
`newZip = zipfile.ZipFile(unmapped_read1gz, 'w', allowZip64 = True)`
